# Generated by Django 2.1.2 on 2018-10-10 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 19, 56, 16, 459870, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='Some task', max_length=100),
        ),
    ]
